// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGfaBgSBJnREVLltqSVrg3fnKtXXhAnRM',
    appId: '1:958999170347:web:a1339763a86242b5e9c96e',
    messagingSenderId: '958999170347',
    projectId: 'piensa-play-6b08c',
    authDomain: 'piensa-play-6b08c.firebaseapp.com',
    storageBucket: 'piensa-play-6b08c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWVQlbOC85su6tcATEyTxD2Ai20s9kJ0s',
    appId: '1:958999170347:android:bdd040040fb81a78e9c96e',
    messagingSenderId: '958999170347',
    projectId: 'piensa-play-6b08c',
    storageBucket: 'piensa-play-6b08c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5f7wjKhxn_cfbNi41nQA-vkmW7WfbAh4',
    appId: '1:958999170347:ios:9e16c134902df07be9c96e',
    messagingSenderId: '958999170347',
    projectId: 'piensa-play-6b08c',
    storageBucket: 'piensa-play-6b08c.firebasestorage.app',
    iosBundleId: 'com.example.piensaPlay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5f7wjKhxn_cfbNi41nQA-vkmW7WfbAh4',
    appId: '1:958999170347:ios:9e16c134902df07be9c96e',
    messagingSenderId: '958999170347',
    projectId: 'piensa-play-6b08c',
    storageBucket: 'piensa-play-6b08c.firebasestorage.app',
    iosBundleId: 'com.example.piensaPlay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGfaBgSBJnREVLltqSVrg3fnKtXXhAnRM',
    appId: '1:958999170347:web:7846c84dd54666cce9c96e',
    messagingSenderId: '958999170347',
    projectId: 'piensa-play-6b08c',
    authDomain: 'piensa-play-6b08c.firebaseapp.com',
    storageBucket: 'piensa-play-6b08c.firebasestorage.app',
  );

}